### ISSUE TITLE
Considerations for expiration / renewal text 8(a) in v.1.2.1

### ISSUE THREAD

**Issue by compleatang** [cantingtribe/nda.cantingtribe.com#2]
[@kemitchell I'm not totally sure if this is the right repository for gathering specific textual feedback on CantingTribe NDA text, but if It isn't then please route me to the correct location.]

I have a thought on the way that expiration / renewal is textually drafted in v1.2.1. Text currently reads:

```
Expiration. Unless extended by cosigned, written agreement of the parties, 
this agreement will terminate automatically on the first anniversary of the 
date of this agreement.
```

I understand that the above is fairly boilerplate. However, I also understand that (to me) one of the purposes of the Canting Tribe NDA is to unblock commercial activities by reducing friction at the *beginning* of a business relationship while also providing a *backstop* of cover for the protection of commercially sensitive information over the *course* of a business relationship. 

In practice NDAs are almost always either:
* not *really* in force because the parties decide not to move forward with the business relationship; or
* are practically superceded by the text of a contract that governs the business relationship (which would rarely *not* contain confidential information coverage). 

While there are edge and corner cases where an NDA could be operative despite the above practicalities, at least in my lawyering and businessing I cannot think of a time when the above hasn't taken place. 

This links with the expiration thoughts which is that if:

a. the point of the Canting Tribe NDA is to become a "community centric pre-aproved form" that "just works"; and
b. once it has been signed once it should be simple to sign again (if needed) 

then I'm curious for folks thoughts on wording such as the below.

```
Expiration. This agreement will terminate automatically on the first anniversary 
of the date of this agreement.
```

By removing the extension portion of the clause, then users of the NDA can have a lot more certainty as to whether the NDA is actually operative (something basically no one tracks, but at Monax we're working on enabling). In the real world, if the NDA was **not** supplanted by a commercial contract covering confidential information and **actually** did need to be renewed and if it was already an approved form by the parties then it would be simply a matter of executing a new form -- which in reality require the exact same amount of effort by the users of the form (albeit less ambiguous from a commercial realities perspective in my view).

The secondary advantage here is that as case law / privacy law and other concerns move perhaps within the year's initial term of the NDA there was something which required a new version of the CT NDA, with the above textual adjustment the parties would have a default position of non-extension and sign a new form, and in such a case this would "force" them to capture the necessary upgrades.

**Comment by kemitchell** [comment]
@compleatang wherever's most convenient for you to feed back, that's where you should do so. Greatly appreciate this issue and your proposal.

I generally agree with your field report on NDA behavior in the wild. I would add only that some high-transaction-volume businesses prefer to sign definitive agreements that leave pre-deal NDAs in place, reciting its existence and (hopefully) carving it out of the integration clause. Partly to reduce the scope of the definitive agreement. Partly to avoid disparity in confidentiality terms, where they do lots of transactions of different types, each with its own form definitive agreement. Basically, it's DRY in corporate procurement.

I think the crux here is what Canting Tribe's _default_ should be:

1. As written, the form continues forever, until somebody terminates.

2. We could flip it, and make the term one year, and allow definitive agreements to amend if they want to keep those terms in place.

3. We could make term a blank on the first page, where the proposer can write "one year" or "perpetual".

I am very open to changing.

@anseljh, any preference?

**Comment by kemitchell** [comment]
CC: @rickcolosimo

**Comment by compleatang** [comment]
Fair point on the DRY aspect. I can see that being efficient. In general the focus of my comments was largely on trying to bring an element of type safety to the length of this; and yes you're correct this is really a conversation regarding a sensible default. 

Given the use case you cite I can see length as a parameter (my wording for your option 3) being a sensible default. Your option 2 remains my preference given the overall goals of this form; however 3 would also work in our circumstance. 

I would strongly argue against 1 as it basically brings a level of uncertainty which is hard for me to reason with. In my experience very few people track NDAs in force, much less effectively terminate them; therefore they are unwittingly exposing themselves to (small, but not zero) perpetual risk.

**Comment by kemitchell** [comment]
@compleatang I think I'd prefer option 2 (one year fixed term) to option 3 (make term a blank to fill in), out of general preference to minimize blanks. But I'd like to hear from @anseljh and @rickcolosimo.

**Comment by rickcolosimo** [comment]
To me, there's no substantive difference between these two terms:

> Expiration. Unless extended by cosigned, written agreement of the parties, this agreement will terminate automatically on the first anniversary of the date of this agreement.
 
and

> Expiration. This agreement will terminate automatically on the first anniversary 
of the date of this agreement.

As I read them, the agreement will terminate in 1 year and under all circumstances the parties can amend the agreement. The only difference is that the first version signals to users that they can amend and limits the amendment to a mutually signed writing to avoid oral amendments.

This last language is duplicative of 9(d):

> Written Amendments and Waivers. The parties will amend this agreement only
by cosigned, written agreement. The parties will waive parts of this agreement, if
at all, only by written waiver describing the specific terms waived and in what
particular instance, signed by the party waiving.

As for the three options, I agree that option 2 is definitely simpler for users and the simpler version is better for that because it's not particularly necessary.

All said, then, I think the shorter provision suggested by @compleatang is best.

**Comment by compleatang** [comment]
@rickcolosimo BTW, pleasure to meet you via a GH issue! 

FWIW, didn't mean to imply that the legal effect was different between the provisions. Agree that the end state ends up in the same place.

**Comment by kemitchell** [comment]
Let's set specific language aside for now. We can torture that poor language to death in a pull request later :-P

@anseljh, unless you object to making a fixed, one-year term the default, I will release a 2.0.0 making that change. (Watch this repo for releases if you like.) I won't touch anybody's listing at https://nda.cantingtribe.com/#companies without their confirmation.

**Comment by kemitchell** [comment]
Oh! I've got my wires crossed here. The form _already_ expires on the first anniversary. This is entirely about the language.

**Comment by kemitchell** [comment]
All: I'm in favor of shortening and simplifying the language. PR coming.
